juanDuqueS/Proyecto-Yaz

- front-end-yaz/src/components/Login.vue
- front-end-yaz/src/components/Menu.vue
- front-end-yaz/src/components/Payment.vue
- front-end-yaz/src/components/PurchaseSummary.vue
- front-end-yaz/src/components/Register.vue
- front-end-yaz/src/components/Shop.vue
- front-end-yaz/src/store/index.js
What: Fix-payment-component
why: design requests had to be implemented in the payment component
> fix-payment-component

- back-end-yaz/src/server/controllers/ItemController.js
- back-end-yaz/src/server/services/ItemService.js
Implementing services for item
What: trying to implement the services for the endpoints to connect with the database
Why: to have a functional API with its crud
> implementing services for item

- back-end-yaz/src/server/controllers/ItemController.js
- back-end-yaz/src/server/controllers/Payment_itemsController.js
- back-end-yaz/src/server/controllers/Payment_serviceController.js
- back-end-yaz/src/server/controllers/ServiceController.js
- back-end-yaz/src/server/controllers/UserController.js
- back-end-yaz/src/server/services/ItemService.js
- back-end-yaz/src/server/services/Payment_itemsService.js
- back-end-yaz/src/server/services/Payment_serviceService.js
- back-end-yaz/src/server/services/ServiceService.js
- back-end-yaz/src/server/services/UserService.js
What: finished the rest of the services for each one of the entities
why: to have the connection with de database and the endpoints
Yaz 23/terminate the entities services
> Yaz 23/terminate the entities services

- back-end-yaz/src/server/controllers/ItemController.js
- back-end-yaz/src/server/controllers/Payment_itemsController.js
- back-end-yaz/src/server/controllers/Payment_serviceController.js
- back-end-yaz/src/server/controllers/ServiceController.js
- back-end-yaz/src/server/controllers/UserController.js
what: fixed some http codes that was'nt apropiate
why: to give good answers 
Yaz-28: Review and fix the error codes returned by the API
Pd: sry for the gramatical errors in the name branch 🤕
> fixing some http codes

- front-end-yaz/src/components/Calendar.vue
- front-end-yaz/src/components/ChangeEvent.vue
- front-end-yaz/src/store/index.js
What:  Calendar changes
Why:  Based on the requirements requested by the client, changes in the calendar are required
Ticket:  YAZ-22
> Yaz 22 calendar changes

- back-end-yaz/src/index.js
- back-end-yaz/src/server/controllers/ItemController.js
- back-end-yaz/src/server/controllers/Payment_itemsController.js
- back-end-yaz/src/server/controllers/Payment_serviceController.js
- back-end-yaz/src/server/controllers/ServiceController.js
- back-end-yaz/src/server/controllers/UserController.js
- back-end-yaz/src/server/services/ItemService.js
- back-end-yaz/src/server/services/Payment_itemsService.js
- back-end-yaz/src/server/services/Payment_serviceService.js
- back-end-yaz/src/server/services/ServiceService.js
- back-end-yaz/src/server/services/UserService.js
What: solve errors in the endpoint
why: To have a functional conection
Yaz-32/solve endpoint errors
> Yaz 32/solve endpoint errors

- back-end-yaz/src/server/src/config/config.js
- back-end-yaz/src/server/src/models/index.js
What: SSL configuration and heroku env config
Why: Do the conection with heroku
YAZ-014
> Add ssl configuration and heroku env config

- front-end-yaz/package-lock.json
- front-end-yaz/package.json
- front-end-yaz/src/components/Register.vue
- front-end-yaz/src/services/Api.js
- front-end-yaz/src/services/UsersService.js
What: Implement Axios
Why: because it is necessary to connect to the back
Ticket: YAZ-41
> Yaz 41 implement axios

- back-end-yaz/package-lock.json
- back-end-yaz/package.json
- back-end-yaz/test/test.js
What: created another unit test
Why: to have a better code
Yaz 39: implement unit test for the API
> Yaz 39/implement unit test for api

- front-end-yaz/src/components/Register.vue
- front-end-yaz/src/services/Api.js
What:  Fix Register Component
Why:   The registry interface is outdated
Ticket: YAZ-48
> YAZ-48-Fix-register-component

- back-end-yaz/src/server/controllers/UserController.js
- back-end-yaz/src/server/routes/UserRoutes.js
- back-end-yaz/src/server/services/UserService.js
What: Creating some necesary routes
Why: To have complete communication within back and front
Yaz 45 Create complementary routes
> Yaz 45/complementary routes

- front-end-yaz/src/App.vue
- front-end-yaz/src/components/Login.vue
- front-end-yaz/src/components/Shop.vue
- front-end-yaz/src/services/UsersService.js
- front-end-yaz/src/store/index.js
What: Login: front and back connection
Why: Is required to do work the application
Ticket: YAZ-51
> login-front-and-back-connection

- back-end-yaz/src/server/src/models/service.js
- back-end-yaz/src/server/src/models/user.js
What: Make changes to database.
Why: Because it was needed to change some attributes types to work with a vuetify component.
Ticket: YAZ-49
> Make changes in data base

- back-end-yaz/src/server/controllers/UserController.js
- back-end-yaz/src/server/routes/UserRoutes.js
- back-end-yaz/src/server/services/UserService.js
What: Created requerid route for the front
Why: To have a functional connection
Yaz-45 Create complementary routes
> GetAllUsersByType route created

- back-end-yaz/src/index.js
- back-end-yaz/src/server/controllers/ItemController.js
- back-end-yaz/src/server/controllers/Payment_itemsController.js
- back-end-yaz/src/server/controllers/Payment_serviceController.js
- back-end-yaz/src/server/controllers/ServiceController.js
- back-end-yaz/src/server/controllers/UserController.js
- back-end-yaz/src/server/services/ItemService.js
- back-end-yaz/src/server/services/Payment_itemsService.js
- back-end-yaz/src/server/services/Payment_serviceService.js
- back-end-yaz/src/server/services/ServiceService.js
- back-end-yaz/src/server/services/UserService.js
- back-end-yaz/test/serviceTest.js
What: Fixed the api responses when errors ocurred 
Why: To have a better API
Yas 54: Fix API response errors
> Yaz 54/fix api response errors

- front-end-yaz/package-lock.json
- front-end-yaz/package.json
- front-end-yaz/src/App.vue
- front-end-yaz/src/components/Register.vue
- front-end-yaz/src/services/firebase.js
- front-end-yaz/src/store/index.js
What: upload images to the cloud
Why:  to have a better user experience
Yaz 53/upload image to the cloud
> Yaz 53/upload image to the cloud

- front-end-yaz/src/App.vue
- front-end-yaz/src/components/Shop.vue
Fix front to use images from cloud
> Fix front to use images from cloud

- front-end-yaz/package-lock.json
- front-end-yaz/src/App.vue
- front-end-yaz/src/components/Calendar.vue
- front-end-yaz/src/components/Login.vue
- front-end-yaz/src/components/Menu.vue
- front-end-yaz/src/components/Register.vue
What: Fix register component
Why: Is required to do work the application
Ticket: YAZ-52
> Yaz 52 fix register component

- front-end-yaz/src/App.vue
- front-end-yaz/src/components/EditUser.vue
- front-end-yaz/src/components/Menu.vue
- front-end-yaz/src/router/index.js
- front-end-yaz/src/services/UsersService.js
What:  Changes on the dropdown menu
Why:  Is required to do work the users components
Ticket:  YAZ-63
> YAZ-63 changes on the dropdown menu

- front-end-yaz/src/components/Shop.vue
What: Fix cards from the shop
Why: The cards component was working incompletely
Ticket: YAZ-64
Dropdown description:
Out of stock:
> Fix cards from the shop

- back-end-yaz/src/index.js
- back-end-yaz/test/itemTest.js
- back-end-yaz/test/payment_ItemTest.js
- back-end-yaz/test/payment_ServiceTest.js
- back-end-yaz/test/serviceTest.js
- front-end-yaz/src/services/EventsService.js
- front-end-yaz/src/services/ItemsService.js
What: Fixed route names
Why: To have a more consistent API
Yaz 66 - Fix route names
> Fixed routes names
